.\"                                      Hey, EMACS: -*- nroff -*-
.TH XOURNAL 1 "November 8, 2009"
.SH NAME
xournal \- GTK+ Application for note taking
.SH SYNOPSIS
.B xournal
.RI [ file ]
.br
.SH DESCRIPTION
This manual page briefly documents the
.B xournal
command.
.PP
\fBXournal\fP is a GTK+ application for notetaking, sketching and
keeping a journal using a stylus. It can also be used to
add annotations to PDF files and graphics files.  It takes no options.
.PP
The Xournal HTML manual may be found at
file://usr/share/doc/xournal/manual.html
.SH AUTHOR
xournal was written by Denis Auroux <auroux@math.mit.edu>.
.PP
This manual page was originally written by 
Mathieu Bouchard <mbouchar@bioinfo.ulaval.ca>,
for the Debian project (but may be used by others).
